local Plug = vim.fn['plug#']

vim.call('plug#begin')
Plug('nvim-treesitter/nvim-treesitter', { ['do'] = ':TSUpdate'})
Plug('https://github.com/junegunn/vim-easy-align.git')
Plug('nvim-lua/plenary.nvim')
Plug('nvim-telescope/telescope.nvim', { ['tag'] = '0.1.8' })
Plug('nvim-tree/nvim-tree.lua')
Plug('nvim-tree/nvim-web-devicons')
Plug('tpope/vim-fireplace', { ['for'] = 'clojure' })
Plug('tpope/vim-fugitive')
Plug('tpope/vim-commentary')
Plug('catppuccin/nvim', { ['as'] = 'catppuccin' })
Plug('nvim-lualine/lualine.nvim')
Plug('christoomey/vim-tmux-navigator')
Plug('preservim/vimux')
Plug('airblade/vim-gitgutter')
Plug('williamboman/mason.nvim')
Plug('williamboman/mason-lspconfig.nvim')
Plug('neovim/nvim-lspconfig')
Plug('hrsh7th/cmp-nvim-lsp')
Plug('hrsh7th/cmp-buffer')
Plug('hrsh7th/cmp-path')
Plug('hrsh7th/cmp-cmdline')
Plug('hrsh7th/nvim-cmp')
Plug('kdheepak/lazygit.nvim')
Plug('mfussenegger/nvim-jdtls')
vim.call('plug#end')

require('plugins.lazygit')
require('plugins.lualine')
require('plugins.mason-lspconfig')
require('plugins.nvim-cmp')
require('plugins.nvim-tree')
require('plugins.nvim-treesitter')
require('plugins.telescope')
